[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
rt = "0.16.0"
tokio = {version = "1.44.2", features = ["full"]}
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.83.0"
dotenv = "0.15.0"
